    
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-scripts/errormarker.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

# kakko
[[plugins]]
repo = 'cohama/lexima.vim'


# local load
[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'tpope/vim-surround'

# comment out
[[plugins]]
repo = 'sakuraiyuta/commentout.vim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# go lang
[[plugins]]
repo = 'fatih/vim-go'

